# Test playbook
---

- hosts: all
  become: true
  vars:
    NS: TRAVIS
  roles:
    - role: repository
    - role: gridinit
      openio_gridinit_namespace: "{{ NS }}"
    - role: memcached
      openio_memcached_namespace: "{{ NS }}"
    - role: role_under_test
      openio_oioswift_namespace: "{{ NS }}"
      openio_oioswift_bind_interface: "{{ ansible_default_ipv4.alias }}"
      openio_oioswift_pipeline: "{{ pipeline_tempauth }}"
      openio_oioswift_filter_tempauth:
        use: "egg:swift#tempauth"
        user_travis_ci: "TRAVIS_PASS .admin"
      openio_oioswift_filter_cache:
        use: "egg:swift#memcache"
        memcache_servers: "{{ openio_oioswift_bind_address }}:6019"
        memcache_max_connections: 50


...
